// @purpose  韓国語漢字語と日本語漢字語の音対応パターン学習データ
// WHY: 韓国語と日本語は漢字語彙の割合が高く、パッチム（韻尾）の対応規則さえ覚えれば
// 日本語話者は他言語話者より遥かに速く韓国語漢字語を推測・習得できる。この対応関係自体を
// 独立した学習コンテンツとして扱う（単なる単語暗記ではなく規則の理解を目的とする）。

const HANJA_PATTERNS = [
  {
    id: "g",
    pattern: "パッチム「ㄱ」→ 促音（っ）＋か行",
    explanation: "韓国語のパッチムㄱ（入声）で終わる漢字音は、日本語では「っ」＋か行の音になることが多い。",
    pairs: [
      { hanja: "學校", korean: "학교", japanese: "がっこう", meaning: "学校" },
      { hanja: "國家", korean: "국가", japanese: "こっか", meaning: "国家" },
      { hanja: "目的", korean: "목적", japanese: "もくてき", meaning: "目的" },
      { hanja: "各自", korean: "각자", japanese: "かくじ", meaning: "各自" },
      { hanja: "樂器", korean: "악기", japanese: "がっき", meaning: "楽器" },
      { hanja: "直角", korean: "직각", japanese: "ちょっかく", meaning: "直角" },
      { hanja: "特急", korean: "특급", japanese: "とっきゅう", meaning: "特急" },
      { hanja: "約束", korean: "약속", japanese: "やくそく", meaning: "約束" },
      { hanja: "食堂", korean: "식당", japanese: "しょくどう", meaning: "食堂" },
      { hanja: "育兒", korean: "육아", japanese: "いくじ", meaning: "育児" },
      { hanja: "白紙", korean: "백지", japanese: "はくし", meaning: "白紙" },
      { hanja: "目擊", korean: "목격", japanese: "もくげき", meaning: "目撃" },
    ],
  },
  {
    id: "l",
    pattern: "パッチム「ㄹ」→ 促音（っ）／つ＋た・ぱ行",
    explanation: "韓国語のパッチムㄹ（入声）で終わる漢字音は、日本語では「つ」、後ろの音によっては促音「っ」になる。",
    pairs: [
      { hanja: "發音", korean: "발음", japanese: "はつおん", meaning: "発音" },
      { hanja: "失敗", korean: "실패", japanese: "しっぱい", meaning: "失敗" },
      { hanja: "結婚", korean: "결혼", japanese: "けっこん", meaning: "結婚" },
      { hanja: "活動", korean: "활동", japanese: "かつどう", meaning: "活動" },
      { hanja: "出發", korean: "출발", japanese: "しゅっぱつ", meaning: "出発" },
      { hanja: "決定", korean: "결정", japanese: "けってい", meaning: "決定" },
      { hanja: "密接", korean: "밀접", japanese: "みっせつ", meaning: "密接" },
      { hanja: "活發", korean: "활발", japanese: "かっぱつ", meaning: "活発" },
      { hanja: "說明", korean: "설명", japanese: "せつめい", meaning: "説明" },
      { hanja: "必要", korean: "필요", japanese: "ひつよう", meaning: "必要" },
      { hanja: "實力", korean: "실력", japanese: "じつりょく", meaning: "実力" },
      { hanja: "出勤", korean: "출근", japanese: "しゅっきん", meaning: "出勤" },
    ],
  },
  {
    id: "m",
    pattern: "パッチム「ㅁ」→ ん",
    explanation: "韓国語のパッチムㅁで終わる漢字音は、日本語では撥音「ん」になる。",
    pairs: [
      { hanja: "感謝", korean: "감사", japanese: "かんしゃ", meaning: "感謝" },
      { hanja: "男女", korean: "남녀", japanese: "だんじょ", meaning: "男女" },
      { hanja: "心理", korean: "심리", japanese: "しんり", meaning: "心理" },
      { hanja: "音樂", korean: "음악", japanese: "おんがく", meaning: "音楽" },
      { hanja: "森林", korean: "삼림", japanese: "しんりん", meaning: "森林" },
      { hanja: "深刻", korean: "심각", japanese: "しんこく", meaning: "深刻" },
      { hanja: "感動", korean: "감동", japanese: "かんどう", meaning: "感動" },
      { hanja: "金額", korean: "금액", japanese: "きんがく", meaning: "金額" },
      { hanja: "任務", korean: "임무", japanese: "にんむ", meaning: "任務" },
      { hanja: "侵略", korean: "침략", japanese: "しんりゃく", meaning: "侵略" },
    ],
  },
  {
    id: "n",
    pattern: "パッチム「ㄴ」→ ん",
    explanation: "韓国語のパッチムㄴで終わる漢字音も、日本語では撥音「ん」になる（ㅁと同じ結果になるので区別が必要）。",
    pairs: [
      { hanja: "安全", korean: "안전", japanese: "あんぜん", meaning: "安全" },
      { hanja: "電話", korean: "전화", japanese: "でんわ", meaning: "電話" },
      { hanja: "新聞", korean: "신문", japanese: "しんぶん", meaning: "新聞" },
      { hanja: "運轉", korean: "운전", japanese: "うんてん", meaning: "運転" },
      { hanja: "眞實", korean: "진실", japanese: "しんじつ", meaning: "真実" },
      { hanja: "反對", korean: "반대", japanese: "はんたい", meaning: "反対" },
      { hanja: "現在", korean: "현재", japanese: "げんざい", meaning: "現在" },
      { hanja: "演技", korean: "연기", japanese: "えんぎ", meaning: "演技" },
      { hanja: "訓練", korean: "훈련", japanese: "くんれん", meaning: "訓練" },
      { hanja: "完全", korean: "완전", japanese: "かんぜん", meaning: "完全" },
    ],
  },
  {
    id: "ng",
    pattern: "パッチム「ㅇ」→ 長音（う／い）",
    explanation: "韓国語のパッチムㅇ（鼻音ŋ）で終わる漢字音は、日本語では長音になることが多い。",
    pairs: [
      { hanja: "空港", korean: "공항", japanese: "くうこう", meaning: "空港" },
      { hanja: "映畫", korean: "영화", japanese: "えいが", meaning: "映画" },
      { hanja: "放送", korean: "방송", japanese: "ほうそう", meaning: "放送" },
      { hanja: "成功", korean: "성공", japanese: "せいこう", meaning: "成功" },
      { hanja: "中央", korean: "중앙", japanese: "ちゅうおう", meaning: "中央" },
      { hanja: "健康", korean: "건강", japanese: "けんこう", meaning: "健康" },
      { hanja: "想像", korean: "상상", japanese: "そうぞう", meaning: "想像" },
      { hanja: "平等", korean: "평등", japanese: "びょうどう", meaning: "平等" },
      { hanja: "應用", korean: "응용", japanese: "おうよう", meaning: "応用" },
      { hanja: "講義", korean: "강의", japanese: "こうぎ", meaning: "講義" },
    ],
  },
  {
    id: "none",
    pattern: "パッチムなし → そのまま対応",
    explanation: "パッチムがない開音節の漢字音は、日本語でも比較的近い形で対応することが多い。",
    pairs: [
      { hanja: "家具", korean: "가구", japanese: "かぐ", meaning: "家具" },
      { hanja: "料理", korean: "요리", japanese: "りょうり", meaning: "料理" },
      { hanja: "地圖", korean: "지도", japanese: "ちず", meaning: "地図" },
      { hanja: "無理", korean: "무리", japanese: "むり", meaning: "無理" },
      { hanja: "自由", korean: "자유", japanese: "じゆう", meaning: "自由" },
      { hanja: "主義", korean: "주의", japanese: "しゅぎ", meaning: "主義" },
      { hanja: "都市", korean: "도시", japanese: "とし", meaning: "都市" },
      { hanja: "未來", korean: "미래", japanese: "みらい", meaning: "未来" },
      { hanja: "準備", korean: "준비", japanese: "じゅんび", meaning: "準備" },
      { hanja: "家事", korean: "가사", japanese: "かじ", meaning: "家事" },
    ],
  },
  {
    id: "dueum",
    pattern: "頭音法則：語頭の「라/러/로/료/리」「냐/녀」→「나/노/요/이」「야/여」",
    explanation: "同じ漢字でも、単語の一番最初に来るときだけ発音（表記）が変わる韓国語独自の規則。ㄹで始まる漢字音は語頭でㄴまたはㅇに、ㄴ＋야行の漢字音は語頭でㅇに変わる。単語の途中（二文字目以降）では元の音のまま。日本語の音読みにはこの現象がないため、対応パターンとして知っておくと語頭変化した単語も推測しやすくなる。",
    pairs: [
      { hanja: "女子", korean: "여자（語中: 남녀の녀のまま）", japanese: "じょし", meaning: "女子" },
      { hanja: "老人", korean: "노인（語中: 경로の로のまま）", japanese: "ろうじん", meaning: "老人" },
      { hanja: "理由", korean: "이유（語中: 무리の리のまま）", japanese: "りゆう", meaning: "理由" },
      { hanja: "良心", korean: "양심（語中: 불량の량のまま）", japanese: "りょうしん", meaning: "良心" },
      { hanja: "樂園", korean: "낙원（語中: 쾌락の락のまま）", japanese: "らくえん", meaning: "楽園" },
      { hanja: "歷史", korean: "역사（語中: 경력の력のまま）", japanese: "れきし", meaning: "歴史" },
    ],
  },
];
